.TH REMINDME 1 "17 February 2019" "Remindme CLI"
.SH NAME
 remindme \- Send yourself reminders at a specific time on one or more devices
.SH SYNOPSIS
.B remindme
[\fB\-t\fR \fITIME\fR]
[\fB\-\-at \fITIME\fR]
[\fB\-i\fR \fIPERIOD\fR]
[\fB\-\-in\fR \fIPERIOD\fR]
.IR message
.PP
.B remindme 
[\fB\-l \fIFLAGS\fR]
[\fB\-\-list \fIFLAG\fR]
.SH DESCRIPTION
.B remindme\fR queues a message to be sent back to you at a give time or duration.
.SH OPTIONS
.TP
.BR \-t ", " \-\-at =\fITIME\fR
Sets the time to send the reminder. Time is expected to be in ISO 8601 format. 
All dates will be read in your local timezone and converted to UTC. 
.PP
.RS
.B Example: \fI2038-01-19T03:14:07\fR
.RE
.TP
.BR \-i ", " \-\-in =\fIPERIOD\fR
Queues the reminder to be sent after a period of time. 
Period format is [NUMBER][DHMS]. 
.PP
.nf
.RS
NUMBER \- Period amount. Must be whole
D \- in N days
H \- in N hours
M \- in N minutes
S \- in N seconds
.RE
.fi
.TP
.BR \-l ", " \-\-list=\fIFLAG\fR
Lists your reminders, optionally by flag.
.SH EXAMPLES
Remind yourself to take your laptop with you after work.
.PP
.RS
.nf
$ remindme --at 2038-01-17T17:00:00 "Take your laptop home!"
.fi
.RE
.PP
Remind yourself in 30 minutes to check the deployment status.
.PP
.RS
.nf
$ remindme --in 30M "Check if deployment succeeded."
.fi
.RE
.PP
Print your reminders
.PP
.RS
.nf
$ remindeme -l
  n 1029301391 remember to update manpage!
.PP
$ remindme --list=m
  m 1049130139 Don't miss this reminder!
.fi
.RE
.SH AUTHOR
Writen by Stephen Enders
.SH COPYRIGHT
MIT License
.PP
Copyright (c) 2019 Stephen Enders
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
